//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dCareProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 看診紀錄表
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 看診紀錄表()
        {
            this.預約表 = new HashSet<預約表>();
        }
    
        public int ID { get; set; }
        public Nullable<float> 體溫 { get; set; }
        public Nullable<int> 血氧 { get; set; }
        public Nullable<int> 體重 { get; set; }
        public Nullable<int> 脈搏 { get; set; }
        public System.DateTime 健檢時間 { get; set; }
        public string 看診紀錄 { get; set; }
        public string 用藥紀錄 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<預約表> 預約表 { get; set; }
    }
}
