//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dCareProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 看診點
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public 看診點()
        {
            this.病人 = new HashSet<病人>();
        }
    
        public int ID { get; set; }
        public string 名稱 { get; set; }
        public string 電話 { get; set; }
        public string 地址 { get; set; }
        public string 負責人 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<病人> 病人 { get; set; }
    }
}
