//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dCareProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class 預約表
    {
        public int ID { get; set; }
        public Nullable<int> 病人ID { get; set; }
        public Nullable<int> 醫生ID { get; set; }
        public Nullable<int> 看診紀錄表ID { get; set; }
        public Nullable<System.DateTime> 登記時間 { get; set; }
        public string 看診結果 { get; set; }
        public string 報到結果 { get; set; }
    
        public virtual 看診紀錄表 看診紀錄表 { get; set; }
        public virtual 病人 病人 { get; set; }
        public virtual 醫生 醫生 { get; set; }
    }
}
